package util

import (
	"testing"
)

func TestSecureStringGenerator(t *testing.T) {
	uniqueSecrets := make(map[string]bool)
	for count := 0; count < 5; count++ {
		secretKey, err := GenerateSecureString(20)
		if err == nil {
			uniqueSecrets[secretKey] = true
		}
	}
	want := 5
	got := len(uniqueSecrets)
	if want != got {
		t.Error("The secrets generated by GenerateSecureString() arent unique")
	}

}
